trigger:
  - master
pr:
  - master

variables:
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    NX_BRANCH: 'master'
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestNumber)

jobs:
  - job: agent
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      parallel: 4
    steps:
      - script: npm i
      - script: pnpx nx-cloud start-agent

  - job: main
    pool:
      vmImage: 'ubuntu-latest'
    condition: ne(variables['Build.Reason'], 'PullRequest'))
    steps:
      - script: npm i
      - script: npx nx-cloud start-ci-run
      - script: npx nx affected --base=HEAD~1 --target=build --parallel --max-parallel=3
      - script: npx nx affected --base=HEAD~1 --target=test --parallel --max-parallel=2
      - script: npx nx-cloud stop-all-agents

  - job: pr
    pool:
      vmImage: 'ubuntu-latest'
    condition: eq(variables['Build.Reason'], 'PullRequest'))
    steps:
      - script: npm i
      - script: npx nx-cloud start-ci-run
      - script: npx nx affected --target=build --parallel --max-parallel=3
      - script: npx nx affected --target=test --parallel --max-parallel=2
      - script: npx nx-cloud stop-all-agents