# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cache@2
  displayName: Cache node_modules
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
    path: $(Build.SourcesDirectory)/node_modules
    cacheHitVar: CACHE_RESTORED

- task: Npm@1
  displayName: 'Install the dependencies'
  inputs:
    command: custom
    verbose: false
    customCommand: 'ci'
  condition: ne(variables.CACHE_RESTORED, 'true')

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    ng build --prod
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'dist'
