export const MockCountries = [
  {id: 232, value: 'United Kingdom', parentId: null},
  {id: 1, value: 'Afghanistan', parentId: null},
  {id: 2, value: 'Åland Islands', parentId: null},
  {id: 3, value: 'Albania', parentId: null},
  {id: 4, value: 'Algeria', parentId: null},
  {id: 5, value: 'American Samoa', parentId: null},
  {id: 6, value: 'Andorra', parentId: null},
  {id: 7, value: 'Angola', parentId: null},
  {id: 8, value: 'Anguilla', parentId: null},
  {id: 9, value: 'Antartica', parentId: null}
];
export const MockDropdownListInfo = {
  result: {
    countries: [
      { id: 232, value: 'United Kingdom', parentId: null },
      { id: 1, value: 'Afghanistan', parentId: null },
      { id: 2, value: 'Åland Islands', parentId: null },
      { id: 3, value: 'Albania', parentId: null },
      { id: 4, value: 'Algeria', parentId: null },
      { id: 5, value: 'American Samoa', parentId: null },
      { id: 6, value: 'Andorra', parentId: null },
      { id: 7, value: 'Angola', parentId: null },
      { id: 8, value: 'Anguilla', parentId: null },
      { id: 9, value: 'Antartica', parentId: null },
      { id: 10, value: 'Antigua and Barbuda', parentId: null },
      { id: 11, value: 'Argentina', parentId: null },
      { id: 12, value: 'Armenia', parentId: null },
      { id: 13, value: 'Aruba', parentId: null },
      { id: 14, value: 'Australia', parentId: null },
      { id: 15, value: 'Austria', parentId: null },
      { id: 16, value: 'Azerbaijan', parentId: null },
      { id: 17, value: 'Bahamas', parentId: null },
      { id: 18, value: 'Bahrain', parentId: null },
      { id: 19, value: 'Bangladesh', parentId: null },
      { id: 20, value: 'Barbados', parentId: null },
      { id: 21, value: 'Belarus', parentId: null },
      { id: 22, value: 'Belgium', parentId: null },
      { id: 23, value: 'Belize', parentId: null },
      { id: 24, value: 'Benin', parentId: null },
      { id: 25, value: 'Bermuda', parentId: null },
      { id: 26, value: 'Bhutan', parentId: null },
      { id: 27, value: 'Bolivia', parentId: null },
      { id: 28, value: 'Bosnia and Herzegovina', parentId: null },
      { id: 29, value: 'Botswana', parentId: null },
      { id: 30, value: 'Bouvet Island', parentId: null },
      { id: 31, value: 'Brazil', parentId: null },
      { id: 32, value: 'British Indian Ocean Territory', parentId: null },
      { id: 33, value: 'Brunei Darussalam', parentId: null },
      { id: 34, value: 'Bulgaria', parentId: null },
      { id: 35, value: 'Burkina Faso', parentId: null },
      { id: 36, value: 'Burundi', parentId: null },
      { id: 37, value: 'Cambodia', parentId: null },
      { id: 38, value: 'Cameroon', parentId: null },
      { id: 39, value: 'Canada', parentId: null },
      { id: 40, value: 'Cape Verde', parentId: null },
      { id: 41, value: 'Cayman Islands', parentId: null },
      { id: 42, value: 'Central African Republic', parentId: null },
      { id: 43, value: 'Chad', parentId: null },
      { id: 44, value: 'Chile', parentId: null },
      { id: 45, value: 'China', parentId: null },
      { id: 46, value: 'Christmas Island', parentId: null },
      { id: 47, value: 'Cocos (Keeling) Islands', parentId: null },
      { id: 48, value: 'Colombia', parentId: null },
      { id: 49, value: 'Comoros', parentId: null },
      { id: 50, value: 'Congo', parentId: null },
      { id: 51, value: 'Congo, Democratic Republic of the', parentId: null },
      { id: 52, value: 'Cook Island', parentId: null },
      { id: 53, value: 'Costa Rica', parentId: null },
      { id: 54, value: 'Côte d\'Ivoire', parentId: null },
      { id: 55, value: 'Croatia', parentId: null },
      { id: 56, value: 'Cuba', parentId: null },
      { id: 247, value: 'Curacao', parentId: null },
      { id: 57, value: 'Cyprus', parentId: null },
      { id: 58, value: 'Czech Republic', parentId: null },
      { id: 59, value: 'Denmark', parentId: null },
      { id: 60, value: 'Djibouti', parentId: null },
      { id: 61, value: 'Dominica', parentId: null },
      { id: 62, value: 'Dominican Republic', parentId: null },
      { id: 63, value: 'Ecuador', parentId: null },
      { id: 64, value: 'Egypt', parentId: null },
      { id: 65, value: 'El Salvador', parentId: null },
      { id: 66, value: 'Equatorial Guinea', parentId: null },
      { id: 67, value: 'Eritrea', parentId: null },
      { id: 68, value: 'Estonia', parentId: null },
      { id: 69, value: 'Ethiopia', parentId: null },
      { id: 70, value: 'Falkland Islands (Malvinas)', parentId: null },
      { id: 71, value: 'Faroe Islands', parentId: null },
      { id: 72, value: 'Fiji', parentId: null },
      { id: 73, value: 'Finland', parentId: null },
      { id: 74, value: 'France', parentId: null },
      { id: 75, value: 'French Guiana', parentId: null },
      { id: 76, value: 'French Polynesia', parentId: null },
      { id: 77, value: 'French Southern Territories', parentId: null },
      { id: 78, value: 'Gabon', parentId: null },
      { id: 79, value: 'Gambia', parentId: null },
      { id: 80, value: 'Georgia', parentId: null },
      { id: 81, value: 'Germany', parentId: null },
      { id: 82, value: 'Ghana', parentId: null },
      { id: 83, value: 'Gibraltar', parentId: null },
      { id: 84, value: 'Greece', parentId: null },
      { id: 85, value: 'Greenland', parentId: null },
      { id: 86, value: 'Grenada', parentId: null },
      { id: 87, value: 'Guadeloupe', parentId: null },
      { id: 88, value: 'Guam', parentId: null },
      { id: 89, value: 'Guatemala', parentId: null },
      { id: 90, value: 'Guernsey', parentId: null },
      { id: 91, value: 'Guinea', parentId: null },
      { id: 92, value: 'Guinea-Bissau', parentId: null },
      { id: 93, value: 'Guyana', parentId: null },
      { id: 94, value: 'Haiti', parentId: null },
      { id: 95, value: 'Heard Island and McDonald Islands', parentId: null },
      { id: 96, value: 'Holy See (Vatican City State)', parentId: null },
      { id: 97, value: 'Honduras', parentId: null },
      { id: 98, value: 'Hong Kong', parentId: null },
      { id: 99, value: 'Hungary', parentId: null },
      { id: 100, value: 'Iceland', parentId: null },
      { id: 101, value: 'India', parentId: null },
      { id: 102, value: 'Indonesia', parentId: null },
      { id: 103, value: 'Iran, Islamic Republic of', parentId: null },
      { id: 104, value: 'Iraq', parentId: null },
      { id: 105, value: 'Ireland', parentId: null },
      { id: 106, value: 'Isle of Man', parentId: null },
      { id: 107, value: 'Israel', parentId: null },
      { id: 108, value: 'Italy', parentId: null },
      { id: 109, value: 'Jamaica', parentId: null },
      { id: 110, value: 'Japan', parentId: null },
      { id: 111, value: 'Jersey', parentId: null },
      { id: 112, value: 'Jordan', parentId: null },
      { id: 113, value: 'Kazakstan', parentId: null },
      { id: 114, value: 'Kenya', parentId: null },
      { id: 115, value: 'Kiribati', parentId: null },
      {
        id: 116,
        value: 'Korea, Democratic People\'s Republic of',
        parentId: null
      },
      { id: 117, value: 'Korea, Republic of', parentId: null },
      { id: 118, value: 'Kuwait', parentId: null },
      { id: 119, value: 'Kyrgyzstan', parentId: null },
      { id: 120, value: 'Lao People\'s Democratic Repulbic', parentId: null },
      { id: 121, value: 'Latvia', parentId: null },
      { id: 122, value: 'Lebanon', parentId: null },
      { id: 123, value: 'Lesotho', parentId: null },
      { id: 124, value: 'Liberia', parentId: null },
      { id: 125, value: 'Libyan Arab Jamahiriya', parentId: null },
      { id: 126, value: 'Liechtenstein', parentId: null },
      { id: 127, value: 'Lithuania', parentId: null },
      { id: 128, value: 'Luxemburg', parentId: null },
      { id: 129, value: 'Macau', parentId: null },
      { id: 130, value: 'Macedonia', parentId: null },
      { id: 131, value: 'Madagascar', parentId: null },
      { id: 132, value: 'Malawi', parentId: null },
      { id: 133, value: 'Malaysia', parentId: null },
      { id: 134, value: 'Maldives', parentId: null },
      { id: 135, value: 'Mali', parentId: null },
      { id: 136, value: 'Malta', parentId: null },
      { id: 137, value: 'Marshall Islands', parentId: null },
      { id: 138, value: 'Martinique', parentId: null },
      { id: 139, value: 'Mauritania', parentId: null },
      { id: 140, value: 'Mauritius', parentId: null },
      { id: 141, value: 'Mayotte', parentId: null },
      { id: 142, value: 'Mexico', parentId: null },
      { id: 143, value: 'Micronesia, Federated States of', parentId: null },
      { id: 144, value: 'Moldova, Republic of', parentId: null },
      { id: 145, value: 'Monaco', parentId: null },
      { id: 146, value: 'Mongolia', parentId: null },
      { id: 147, value: 'Montenegro', parentId: null },
      { id: 148, value: 'Montserrat', parentId: null },
      { id: 149, value: 'Morocco', parentId: null },
      { id: 150, value: 'Mozambique', parentId: null },
      { id: 151, value: 'Myanmar', parentId: null },
      { id: 152, value: 'Namibia', parentId: null },
      { id: 153, value: 'Nauru', parentId: null },
      { id: 154, value: 'Nepal', parentId: null },
      { id: 155, value: 'Netherlands', parentId: null },
      { id: 156, value: 'Netherlands Antilles', parentId: null },
      { id: 157, value: 'New Caledonia', parentId: null },
      { id: 158, value: 'New Zealand', parentId: null },
      { id: 159, value: 'Nicaragua', parentId: null },
      { id: 160, value: 'Niger', parentId: null },
      { id: 161, value: 'Nigeria', parentId: null },
      { id: 162, value: 'Niue', parentId: null },
      { id: 163, value: 'Norfolk Island', parentId: null },
      { id: 164, value: 'Northern Mariana Islands', parentId: null },
      { id: 165, value: 'Norway', parentId: null },
      { id: 166, value: 'Oman', parentId: null },
      { id: 167, value: 'Pakistan', parentId: null },
      { id: 168, value: 'Palau', parentId: null },
      { id: 169, value: 'Palestinian Territory', parentId: null },
      { id: 170, value: 'Panama', parentId: null },
      { id: 171, value: 'Papua New Guinea', parentId: null },
      { id: 172, value: 'Paraguay', parentId: null },
      { id: 173, value: 'Peru', parentId: null },
      { id: 174, value: 'Philippines', parentId: null },
      { id: 175, value: 'Pitcairn Islands', parentId: null },
      { id: 176, value: 'Poland', parentId: null },
      { id: 177, value: 'Portugal', parentId: null },
      { id: 178, value: 'Puerto Rico', parentId: null },
      { id: 179, value: 'Qatar', parentId: null },
      { id: 180, value: 'Réunion', parentId: null },
      { id: 181, value: 'Romania', parentId: null },
      { id: 182, value: 'Russia', parentId: null },
      { id: 183, value: 'Rwanda', parentId: null },
      { id: 184, value: 'Saint Barthelemy', parentId: null },
      { id: 185, value: 'Saint Helena', parentId: null },
      { id: 186, value: 'Saint Kitts and Nevis', parentId: null },
      { id: 187, value: 'Saint Lucia', parentId: null },
      { id: 188, value: 'Saint Martin', parentId: null },
      { id: 189, value: 'Saint Pierre and Miquelon', parentId: null },
      { id: 190, value: 'Saint Vincent and the Grenadines', parentId: null },
      { id: 191, value: 'Samoa', parentId: null },
      { id: 192, value: 'San Marino', parentId: null },
      { id: 193, value: 'Sao Tome and Principe', parentId: null },
      { id: 194, value: 'Saudi Arabia', parentId: null },
      { id: 195, value: 'Senegal', parentId: null },
      { id: 196, value: 'Serbia', parentId: null },
      { id: 197, value: 'Seychelles', parentId: null },
      { id: 198, value: 'Sierra Leone', parentId: null },
      { id: 199, value: 'Singapore', parentId: null },
      { id: 200, value: 'Slovakia', parentId: null },
      { id: 201, value: 'Slovenia', parentId: null },
      { id: 202, value: 'Solomon Islands', parentId: null },
      { id: 203, value: 'Somalia', parentId: null },
      { id: 204, value: 'South Africa', parentId: null },
      {
        id: 205,
        value: 'South Georgia and the South Sandwich Islands',
        parentId: null
      },
      { id: 206, value: 'Spain', parentId: null },
      { id: 207, value: 'Sri Lanka', parentId: null },
      { id: 208, value: 'Sudan', parentId: null },
      { id: 209, value: 'Suriname', parentId: null },
      { id: 210, value: 'Svalbard and Jan Mayen', parentId: null },
      { id: 211, value: 'Swaziland', parentId: null },
      { id: 212, value: 'Sweden', parentId: null },
      { id: 213, value: 'Switzerland', parentId: null },
      { id: 214, value: 'Syrian Arab Republic', parentId: null },
      { id: 215, value: 'Táiwan', parentId: null },
      { id: 216, value: 'Tajikistan', parentId: null },
      { id: 217, value: 'Tanzania, United Republic of', parentId: null },
      { id: 218, value: 'Thailand', parentId: null },
      { id: 219, value: 'Timor-Leste', parentId: null },
      { id: 220, value: 'Togo', parentId: null },
      { id: 221, value: 'Tokelau', parentId: null },
      { id: 222, value: 'Tonga', parentId: null },
      { id: 223, value: 'Trinidad and Tobago', parentId: null },
      { id: 224, value: 'Tunisia', parentId: null },
      { id: 225, value: 'Turkey', parentId: null },
      { id: 226, value: 'Turkmenistan', parentId: null },
      { id: 227, value: 'Turks and Caicos Islands', parentId: null },
      { id: 228, value: 'Tuvalu', parentId: null },
      { id: 229, value: 'Uganda', parentId: null },
      { id: 230, value: 'Ukraine', parentId: null },
      { id: 231, value: 'United Arab Emirates', parentId: null },
      { id: 233, value: 'United States', parentId: null },
      {
        id: 234,
        value: 'United States Minor Outlying Islands',
        parentId: null
      },
      { id: 235, value: 'Uruguay', parentId: null },
      { id: 236, value: 'Uzbekistan', parentId: null },
      { id: 237, value: 'Vanuatu', parentId: null },
      { id: 238, value: 'Venezuela, Bolivarian Republic of', parentId: null },
      { id: 239, value: 'Viet Nam', parentId: null },
      { id: 240, value: 'Virgin Islands, British', parentId: null },
      { id: 241, value: 'Virgin Islands, U.S.', parentId: null },
      { id: 242, value: 'Wallis and Futuna', parentId: null },
      { id: 243, value: 'Western Sahara', parentId: null },
      { id: 244, value: 'Yemen', parentId: null },
      { id: 245, value: 'Zambia', parentId: null },
      { id: 246, value: 'Zimbabwe', parentId: null }
    ],
    titles: {
      '1': 'Mr',
      '2': 'Mrs',
      '3': 'Miss',
      '4': 'Ms',
      '5': 'Lady',
      '6': 'Sir',
      '7': 'Dr',
      '8': 'Lord',
      '100': 'Other'
    },
    telephoneTypes: {
      '1': 'Home',
      '2': 'Work',
      '3': 'Mobile',
      '4': 'Fax',
      '5': 'Other'
    },
    companyTypes: [
      { id: 1, value: 'Company', parentId: null },
      { id: 2, value: 'Other Agent', parentId: null },
      { id: 16, value: 'Property Developer', parentId: null },
      { id: 4, value: 'Relocation Agent', parentId: null },
      { id: 8, value: 'Tradesmen', parentId: null }
    ],
    propertyTypes: [
      { id: 1, value: 'House', parentId: null },
      { id: 2, value: 'Flat', parentId: null }
    ],
    propertyStyles: [
      { id: 1, value: 'Semi-Detached', parentId: 1 },
      { id: 2, value: 'Detached', parentId: 1 },
      { id: 3, value: 'Terraced', parentId: 1 },
      { id: 4, value: 'End Of Terrace', parentId: 1 },
      { id: 6, value: 'Mews', parentId: 1 },
      { id: 5, value: 'Mansion', parentId: 2 },
      { id: 14, value: 'Maisonette', parentId: 2 },
      { id: 7, value: 'Purpose Built', parentId: 2 },
      { id: 8, value: 'Conversion', parentId: 2 },
      { id: 9, value: 'Period Purpose Built', parentId: 2 },
      { id: 12, value: 'Houseboat', parentId: 2 },
      { id: 10, value: 'Garage', parentId: 2 },
      { id: 13, value: 'Land', parentId: 2 },
      { id: 11, value: 'Parking Space', parentId: 2 }
    ],
    regions: [
      { id: 1, value: 'London', parentId: null },
      { id: 2, value: 'Residential Developments', parentId: null }
    ],
    areas: [
      { id: 8, value: 'Balham', parentId: 1 },
      { id: 7, value: 'Battersea', parentId: 1 },
      { id: 5, value: 'BPR', parentId: 1 },
      { id: 3, value: 'Chelsea', parentId: 1 },
      { id: 9, value: 'Clapham', parentId: 1 },
      { id: 1, value: 'Fulham', parentId: 1 },
      { id: 11, value: 'Hammersmith', parentId: 1 },
      { id: 10, value: 'Kensington', parentId: 1 },
      { id: 12, value: 'Notting Hill', parentId: 1 },
      { id: 2, value: 'Pimlico', parentId: 1 },
      { id: 6, value: 'Putney', parentId: 1 },
      { id: 4, value: 'Sth Kensington', parentId: 1 },
      { id: 13, value: 'Southfields and Earlsfield', parentId: 1 },
      { id: 14, value: 'Streatham', parentId: 1 },
      { id: 61, value: 'Queens Park & Kensal Rise', parentId: 1 },
      { id: 59, value: 'Central London', parentId: 2 },
      { id: 53, value: 'City', parentId: 2 },
      { id: 52, value: 'Docklands', parentId: 2 },
      { id: 51, value: 'East London', parentId: 2 },
      { id: 60, value: 'Greater London', parentId: 2 },
      { id: 55, value: 'North London', parentId: 2 },
      { id: 54, value: 'North West London', parentId: 2 },
      { id: 50, value: 'South East London', parentId: 2 },
      { id: 58, value: 'South West London', parentId: 2 },
      { id: 56, value: 'West End', parentId: 2 },
      { id: 57, value: 'West London', parentId: 2 }
    ],
    subAreas: [
      { id: 1, value: 'Nth of Fulham Rd', parentId: 1 },
      { id: 2, value: 'Sth Fulham Rd', parentId: 1 },
      { id: 2, value: 'Belgravia', parentId: 2 },
      { id: 1, value: 'Westminster', parentId: 2 },
      { id: 1, value: 'SW1', parentId: 3 },
      { id: 2, value: 'SW3', parentId: 3 },
      { id: 3, value: 'SW5 (Chelsea)', parentId: 3 },
      { id: 4, value: 'SW7 (Chelsea)', parentId: 3 },
      { id: 5, value: 'SW10', parentId: 3 },
      { id: 1, value: 'SW5 (Sth Kensington)', parentId: 4 },
      { id: 2, value: 'SW7 (Sth Kensington)', parentId: 4 },
      { id: 4, value: 'SW10', parentId: 4 },
      { id: 3, value: 'W8 (Sth Kensington)', parentId: 4 },
      { id: 5, value: 'W14', parentId: 4 },
      { id: 1, value: 'Nth BPR', parentId: 5 },
      { id: 2, value: 'Sth BPR', parentId: 5 },
      { id: 2, value: 'East Putney', parentId: 6 },
      { id: 1, value: 'West Putney', parentId: 6 },
      { id: 1, value: 'Between The Commons', parentId: 7 },
      { id: 2, value: 'Other Areas (Battersea)', parentId: 7 },
      { id: 1, value: 'Nightingale Triangle', parentId: 8 },
      { id: 3, value: 'Streatham', parentId: 8 },
      { id: 4, value: 'Tooting', parentId: 8 },
      { id: 2, value: 'Other Areas (Balham)', parentId: 8 },
      { id: 1, value: 'Abbeville Rd', parentId: 9 },
      { id: 3, value: 'Brixton', parentId: 9 },
      { id: 2, value: 'Other Areas (Clapham)', parentId: 9 },
      { id: 2, value: 'W2 (Kensington)', parentId: 10 },
      { id: 1, value: 'W8 (Kensington)', parentId: 10 },
      { id: 3, value: 'W11 (Kensington)', parentId: 10 },
      { id: 5, value: 'W14 (Kensington)', parentId: 10 },
      { id: 6, value: 'W1H', parentId: 10 },
      { id: 5, value: 'Acton', parentId: 11 },
      { id: 12, value: 'Askew Village', parentId: 11 },
      { id: 10, value: 'Barons Court', parentId: 11 },
      { id: 1, value: 'Brackenbury Village', parentId: 11 },
      { id: 2, value: 'Brook Green', parentId: 11 },
      { id: 3, value: 'Central Hammersmith', parentId: 11 },
      { id: 6, value: 'Chiswick', parentId: 11 },
      { id: 7, value: 'Ealing', parentId: 11 },
      { id: 8, value: 'Ravenscourt Park', parentId: 11 },
      { id: 11, value: 'Stamford Brook', parentId: 11 },
      { id: 4, value: 'Shepherds Bush', parentId: 11 },
      { id: 9, value: 'W14', parentId: 11 },
      { id: 1, value: 'W2 (Notting Hill)', parentId: 12 },
      { id: 5, value: 'W9', parentId: 12 },
      { id: 4, value: 'W10', parentId: 12 },
      { id: 3, value: 'W11 (Notting Hill)', parentId: 12 },
      { id: 2, value: 'W14 (Notting Hill)', parentId: 12 },
      { id: 6, value: 'NW10', parentId: 12 },
      { id: 7, value: 'N1C', parentId: 12 },
      { id: 1, value: 'The Grid', parentId: 13 },
      { id: 2, value: 'Southfields other', parentId: 13 },
      { id: 3, value: 'Earlsfield', parentId: 13 },
      { id: 7, value: 'Raynes Park', parentId: 13 },
      { id: 4, value: 'Wimbledon', parentId: 13 },
      { id: 5, value: 'Wimbledon Park', parentId: 13 },
      { id: 6, value: 'Wandsworth', parentId: 13 },
      { id: 1, value: 'Furzedown', parentId: 14 },
      { id: 2, value: 'Streatham Common', parentId: 14 },
      { id: 3, value: 'Streatham Vale', parentId: 14 },
      { id: 4, value: 'Streatham Hill', parentId: 14 },
      { id: 5, value: 'West Norwood', parentId: 14 },
      { id: 1, value: 'Queens Park', parentId: 61 },
      { id: 2, value: 'Kensal Rise', parentId: 61 },
      { id: 3, value: 'Kensal Green', parentId: 61 },
      { id: 4, value: 'Brondesbury Park', parentId: 61 },
      { id: 5, value: 'Maida Hill', parentId: 61 },
      { id: 6, value: 'Willesden Green', parentId: 61 },
      { id: 2, value: 'Greenwich', parentId: 50 },
      { id: 1, value: 'South Bank', parentId: 50 },
      { id: 1, value: 'East London', parentId: 51 },
      { id: 2, value: 'Docklands', parentId: 52 },
      { id: 1, value: 'City', parentId: 53 },
      { id: 1, value: 'North West London', parentId: 54 },
      { id: 1, value: 'North London', parentId: 55 },
      { id: 1, value: 'West End', parentId: 56 },
      { id: 2, value: 'Acton, Chiswick and Ealing', parentId: 57 },
      { id: 1, value: 'Paddington and St Johns Wood', parentId: 57 },
      { id: 2, value: 'Chelsea and Fulham', parentId: 58 },
      { id: 1, value: 'Clapham, Battersea and Wandsworth', parentId: 58 },
      { id: 3, value: 'Tooting, Balham and Streatham', parentId: 58 },
      { id: 1, value: 'Zone 1', parentId: 59 },
      { id: 2, value: 'Zone 2 (North of river)', parentId: 59 },
      { id: 3, value: 'Zone 2 (South of river)', parentId: 59 },
      { id: 1, value: 'Greater London', parentId: 60 }
    ],
    personWarningStatuses: [
      { id: 1, value: 'None', parentId: null },
      { id: 2, value: 'Deceased', parentId: null },
      { id: 3, value: 'GDPR Removal', parentId: null },
      { id: 4, value: 'No contact wanted', parentId: null },
      { id: 5, value: 'Abusive', parentId: null },
      { id: 100, value: 'Other', parentId: null }
    ]
  }
};
