export enum enumDepartments {
  sales = 10,
  lettings = 11,
  block_management = 12,
  professional_valuations = 13,
  property_management = 14,
  refurbishment_interior_services = 15,
  central_accounts = 51,
  block_management_accounts = 53,
  IT_department = 54,
  tenancy_management = 55,
  printing = 56,
  training = 57,
  HR = 58,
  corporate_services = 60,
  BDD = 90,
  marketing = 91,
}
