export const contactGroupDetailsMock = {
  contactGroupId: 75197,
  contactType: 1,
  addressee: 'Mr & Mrs Steven Younge',
  salutation: 'Mr & Mrs Younge',
  companyId: null,
  companyName: null,
  companyAddress: null,
  companyAmlCompletedDate: null,
  comments: null,
  referenceCount: 2,
  isRelocationAgent: false,
  isSolicitor: false,
  isInventoryClerk: false,
  isMortgageAdvisor: false,
  isEstateAgent: false,
  contactPeople: [
    {
      personId: 81422,
      titleId: 2,
      titleOther: '',
      firstName: 'Wendy',
      middleName: '',
      lastName: 'Younges',
      addressee: 'Mrs Wendy Younges',
      salutation: 'Mrs Younges',
      isMainPerson: true,
      contactByEmail: true,
      contactByPhone: false,
      marketingPreferences: {
        marketBulletin: true,
        events: true,
        newHomes: true,
        offersSurveys: true,
        general: true,
        count: 5,
      },
      amlCompletedDate: '2020-02-19T00:00:00',
      warningStatusId: 1,
      warningStatusComment: null,
      address: {
        addressLines: 'Caroline Close\r\nLondon',
        outCode: 'SW16',
        inCode: '2XU',
        postCode: 'SW16 2XU',
        countryId: 232,
      },
      phoneNumbers: [{ id: 325980, typeId: 3, number: '07980643194', isPreferred: true, sendSMS: true, comments: '' }],
      emailAddresses: [{ id: 183702, email: 'wyounge@dng.co.uk', isPreferred: true, isPrimaryWebEmail: true }],
      personNotes: [],
      info: null,
    },
    {
      personId: 75643,
      titleId: 1,
      titleOther: '',
      firstName: 'Steven',
      middleName: null,
      lastName: 'Younge',
      addressee: 'Mr Steven Younge',
      salutation: 'Mr Younge',
      isMainPerson: false,
      contactByEmail: true,
      contactByPhone: true,
      marketingPreferences: {
        marketBulletin: true,
        events: true,
        newHomes: true,
        offersSurveys: true,
        general: true,
        count: 5,
      },
      amlCompletedDate: null,
      warningStatusId: 1,
      warningStatusComment: null,
      address: {
        addressLines: '31 Caroline Close\r\nLondon',
        outCode: 'SW16',
        inCode: '2XU',
        postCode: 'SW16 2XU',
        countryId: 232,
      },
      phoneNumbers: [{ id: 325979, typeId: 3, number: '07958755998', isPreferred: true, sendSMS: true, comments: '' }],
      emailAddresses: [
        { id: 146580, email: 'w_hutchison@hotmail.com', isPreferred: true, isPrimaryWebEmail: false },
        { id: 254134, email: 'younges@hotmail.com', isPreferred: false, isPrimaryWebEmail: true },
      ],
      personNotes: [],
      info: null,
    },
  ],
  contactNotes: [],
  isAmlCompleted: false,
}
